export const CATEGORIES_STATE_KEY = "categories";
export const NAMESPACE = "CATEGORIES/";

export const FETCH_CATEGORY = `${NAMESPACE}FETCH_CATEGORY`;
export const FETCHING_CATEGORY = `${NAMESPACE}FETCHING_CATEGORY`;
export const FETCH_CATEGORY_SUCCESS = `${NAMESPACE}FETCH_CATEGORY_SUCCESS`;
export const FETCH_CATEGORY_ERROR = `${NAMESPACE}FETCH_CATEGORY_ERROR`;
