export const CATEGORIES_STATE_KEY = "categories";
export const NAMESPACE = "CATEGORIES/";

export const FETCH_CATEGORY = `${NAMESPACE}FETCH_CATEGORY`;
export const FETCHING_CATEGORY = `${NAMESPACE}FETCHING_CATEGORY`;
export const FETCH_CATEGORY_SUCCESS = `${NAMESPACE}FETCH_CATEGORY_SUCCESS`;
export const FETCH_CATEGORY_ERROR = `${NAMESPACE}FETCH_CATEGORY_ERROR`;

export const ADD_CATEGORY = `${NAMESPACE}ADD_CATEGORY`;
export const ADDING_CATEGORY = `${NAMESPACE}ADDING_CATEGORY`;
export const ADD_CATEGORY_SUCCESS = `${NAMESPACE}ADD_CATEGORY_SUCCESS`;
export const ADD_CATEGORY_ERROR = `${NAMESPACE}ADD_CATEGORY_ERROR`;

export const DELETE_CATEGORY = `${NAMESPACE}DELETE_CATEGORY`;
export const DELETEING_CATEGORY = `${NAMESPACE}DELETEING_CATEGORY`;
export const DELETE_CATEGORY_SUCCESS = `${NAMESPACE}DELETE_CATEGORY_SUCCESS`;
export const DELETE_CATEGORY_ERROR = `${NAMESPACE}DELETE_CATEGORY_ERROR`;

