export const TAGGING_STATE_KEY = 'tagging';
export const NAMESPACE = 'TAGGING/';

export const FETCH_BLOGS = `${NAMESPACE}FETCH_BLOGS`;
export const FETCHING_BLOGS = `${NAMESPACE}FETCHING_BLOGS`;
export const FETCH_BLOGS_SUCCESS = `${NAMESPACE}FETCH_BLOGS_SUCCESS`;
export const FETCH_BLOGS_ERROR = `${NAMESPACE}FETCH_BLOGS_ERROR`;

export const SELECT_CATEGORY = `${NAMESPACE}SELECT_CATEGORY`;
