export const TAGGING_STATE_KEY = 'tagging';
export const NAMESPACE = 'TAGGING/';

export const FETCH_BLOGS = `${NAMESPACE}FETCH_BLOGS`;
export const FETCHING_BLOGS = `${NAMESPACE}FETCHING_BLOGS`;
export const FETCH_BLOGS_SUCCESS = `${NAMESPACE}FETCH_BLOGS_SUCCESS`;
export const FETCH_BLOGS_ERROR = `${NAMESPACE}FETCH_BLOGS_ERROR`;

export const SELECT_CATEGORY = `${NAMESPACE}SELECT_CATEGORY`;

export const UPDATE_BLOG = `${NAMESPACE}UPDATE_BLOG`;
export const UPDATING_BLOG = `${NAMESPACE}UPDATING_BLOG`;
export const UPDATE_BLOG_SUCCESS = `${NAMESPACE}UPDATE_BLOG_SUCCESS`;
export const UPDATE_BLOG_ERROR = `${NAMESPACE}UPDATE_BLOG_ERROR`;
