export const APP_STATE_KEY = 'app';
export const NAMESPACE = 'APP/';
export const SET_DATA = `${NAMESPACE}SET_DATA`;
export const FETCH_CATEGORIES = `${NAMESPACE}FETCH_CATEGORIES`;
export const FETCHING_CATEGORIES = `${NAMESPACE}FETCHING_CATEGORIES`;
export const FETCH_CATEGORIES_SUCCESS = `${NAMESPACE}FETCH_CATEGORIES_SUCCESS`;
export const FETCH_CATEGORIES_ERROR = `${NAMESPACE}FETCH_CATEGORIES_ERROR`;
