export const BLOGS_STATE_KEY = "blogs";
export const NAMESPACE = "BLOGS/";

export const FETCH_BLOGS = `${NAMESPACE}FETCH_BLOGS`;
export const FETCHING_BLOGS = `${NAMESPACE}FETCHING_BLOGS`;
export const FETCH_BLOGS_SUCCESS = `${NAMESPACE}FETCH_BLOGS_SUCCESS`;
export const FETCH_BLOGS_ERROR = `${NAMESPACE}FETCH_BLOGS_ERROR`;
export const UPDATE_FILTERS = `${NAMESPACE}UPDATE_FILTERS`;

export const DELETE_BLOG = `${NAMESPACE}DELETE_BLOG`;
export const DELETING_BLOG = `${NAMESPACE}DELETING_BLOG`;
export const DELETE_BLOG_SUCCESS = `${NAMESPACE}DELETE_BLOG_SUCCESS`;
export const DELETE_BLOG_ERROR = `${NAMESPACE}DELETE_BLOG_ERROR`;
